version: "3.9"  # optional since v1.27.0
services:
  database:
    build:
      dockerfile: Dockerfile
      context: ./dump
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "ENV MYSQL_USER=dev"
      - "ENV MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "ENV DOCKER_HOSTNAME=127.0.0.1"
    command: --lower_case_table_names=1
    image: rassur
    ports:
      - "3306:3306"
      - "33060:33060"
    container_name: rassur
